# Generated by Django 5.0 on 2024-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('year', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('premium', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posters')),
            ],
        ),
    ]
